version: '3.8'

services:
  
  api-gateway:
    build: ./api-gateway
    env_file: ./api-gateway/.env
    ports:
      - "3000:3000"
    restart: always


  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  config-service:
    build: ./config-service
    env_file: ./config-service/.env
    restart: always

  read-service:
    build: ./read-service
    env_file: ./read-service/.env
    restart: always

  storage-service:
    build: ./storage-service
    env_file: ./storage-service/.env
    restart: always
  
  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    restart: always
